/* SPDX-License-Identifier: GPL-3.0-or-later */
/*
 * tolunnet — Network Testing & Finalization Engine
 *
 * Starts daemon, pings gateway, tests DNS and HTTP,
 * writes configuration and User-Startup boot blocks.
 */

#include "net_test.h"
#include "boot_block.h"
#include "net_checks.h"
#include "../common/safe_replace.h"
#include "../../include/ipc.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

int tn_format_roadshow_interface(const char *dev, ULONG unit, BOOL is_dhcp,
                                 const char *ip, const char *mask,
                                 char *out_buf, int out_max)
{
    if (!dev || !out_buf || out_max <= 0) return 0;

    int written = 0;
    if (is_dhcp) {
        written = snprintf(out_buf, out_max,
                           "device=%s\n"
                           "unit=%lu\n"
                           "configure=dhcp\n"
                           "iprequests=128\n"
                           "writerequests=128\n"
                           "requiresinitdelay=no\n",
                           dev, (unsigned long)unit);
    } else {
        written = snprintf(out_buf, out_max,
                           "device=%s\n"
                           "unit=%lu\n"
                           "address=%s\n"
                           "netmask=%s\n"
                           "iprequests=128\n"
                           "writerequests=128\n"
                           "requiresinitdelay=no\n",
                           dev, (unsigned long)unit, ip ? ip : "", mask ? mask : "");
    }
    return written;
}

#ifdef __AMIGA__
#include <proto/exec.h>
#include <proto/dos.h>
#include <exec/types.h>
#include <dos/dos.h>
#include <dos/dostags.h>

/* 11m item 1: the name the DNS test resolves. The hermetic bench's
 * netsvc resolver answers it (A -> 10.0.2.2), and on a real install
 * any resolvable name proves the resolver path works. */
#define TN_TEST_DNS_NAME "test.tolunnet.lan"

static BOOL write_text(const char *path, const char *text)
{
    /* 11l item 3: never overwrite in place - the text goes to
     * <file>.tolunnet-new and tn_safe_replace swaps it in, keeping
     * the old content in <file>.tolunnet-bak (one generation). */
    char new_path[300];
    char bak_path[300];
    LONG plen = (LONG)strlen(path);
    LONG len = (LONG)strlen(text);
    LONG w;
    BPTR fh;

    if (plen <= 0 || plen + 20 >= (LONG)sizeof(new_path)) return FALSE;
    strcpy(new_path, path);
    strcat(new_path, ".tolunnet-new");
    strcpy(bak_path, path);
    strcat(bak_path, ".tolunnet-bak");

    fh = Open((CONST_STRPTR)new_path, MODE_NEWFILE);
    if (fh == (BPTR)0) return FALSE;
    w = (len > 0) ? Write(fh, (CONST_APTR)text, len) : 0;
    Close(fh);
    if (w != len) {
        DeleteFile((CONST_STRPTR)new_path);
        return FALSE;
    }
    return tn_safe_replace(new_path, path, bak_path);
}

BOOL tn_write_tolunnet_config(const WizardState *ws)
{
    if (!ws) return FALSE;

    const char *dev_name = "ethernet.device";
    ULONG unit = 0;
    ULONG mtu = 1500;
    if (ws->selected_hw_idx >= 0 && ws->selected_hw_idx < ws->hw_count) {
        dev_name = ws->hw[ws->selected_hw_idx].device_name;
        unit = ws->hw[ws->selected_hw_idx].unit;
        mtu = ws->hw[ws->selected_hw_idx].mtu > 0 ? ws->hw[ws->selected_hw_idx].mtu : 1500;
    }

    char prio_line[32] = "";
    LONG prio = (ws->task_priority != 0) ? ws->task_priority : 5;
    snprintf(prio_line, sizeof(prio_line), "PRIORITY=%ld\n", (long)prio);

    char log_line[96] = "";
    if (ws->log_file[0] != '\0') {
        snprintf(log_line, sizeof(log_line), "LOG=%s\n", ws->log_file);
    }

    char db_line[64] = "";
    if (ws->database_order[0] != '\0') {
        snprintf(db_line, sizeof(db_line), "DATABASE_ORDER=%s\n", ws->database_order);
    }

    char buf[1536];
    /* DNS 2: always in Manual mode; in DHCP mode only as the explicit
     * "Use DHCP DNS, fall back to DNS 2" fallback (TNET-110) */
    const char *dns2_out = (ws->ip_mode == 1) ? ws->dns2_str
                         : (ws->dhcp_fallback_dns2 ? ws->dns2_str : "");
    int len = snprintf(buf, sizeof(buf),
                       "# tolunnet configuration generated by TolunnetSetup\n"
                       "DEVICE=%s\n"
                       "UNIT=%lu\n"
                       "DHCP=%s\n"
                       "IP=%s\n"
                       "NETMASK=%s\n"
                       "GATEWAY=%s\n"
                       "DNS1=%s\n"
                       "DNS2=%s\n"
                       "HOSTNAME=%s\n"
                       "MTU=%lu\n"
                       "DEBUG=1\n"
                       "%s%s%s",
                       dev_name,
                       (unsigned long)unit,
                       (ws->ip_mode == 0) ? "YES" : "NO",
                       (ws->ip_mode == 1) ? ws->ip_str : "",
                       (ws->ip_mode == 1) ? ws->nm_str : "",
                       (ws->ip_mode == 1) ? ws->gw_str : "",
                       (ws->ip_mode == 1) ? ws->dns1_str : "",
                       dns2_out,
                       ws->host_str[0] ? ws->host_str : "amiga",
                       (unsigned long)mtu,
                       prio_line, log_line, db_line);

    if (len <= 0) return FALSE;

    /* Ensure parent directories exist */
    BPTR lock = CreateDir((CONST_STRPTR)"ENVARC:");
    if (lock) UnLock(lock);
    lock = CreateDir((CONST_STRPTR)"ENV:");
    if (lock) UnLock(lock);

    write_text("ENV:tolunnet.config", buf);
    write_text("ENVARC:tolunnet.config", buf);
    write_text("ENV:tolunnet.prefs", buf);
    write_text("ENVARC:tolunnet.prefs", buf);

    /* OS registration: ENV:HostName, ENVARC:HostName, and Domain (no newline) */
    const char *hname = ws->host_str[0] ? ws->host_str : "amiga";
    write_text("ENV:HostName", hname);
    write_text("ENVARC:HostName", hname);

    if (ws->domain_str[0]) {
        write_text("ENV:Domain", ws->domain_str);
        write_text("ENVARC:Domain", ws->domain_str);
    }

    if (ws->write_roadshow_internet) {
        tn_write_roadshow_internet(ws);
    }

    return write_text("DEVS:tolunnet.config", buf);
}

BOOL tn_write_roadshow_internet(const WizardState *ws)
{
    if (!ws || !ws->write_roadshow_internet) return TRUE;

    BPTR lock = CreateDir((CONST_STRPTR)"DEVS:Internet");
    if (lock) UnLock(lock);

    /* DEVS:Internet/name_resolution */
    char nr_buf[512] = "";
    int nr_len = 0;
    if (ws->domain_str[0]) {
        nr_len += snprintf(nr_buf + nr_len, sizeof(nr_buf) - nr_len, "domain %s\n", ws->domain_str);
    }
    if (ws->dns1_str[0]) {
        nr_len += snprintf(nr_buf + nr_len, sizeof(nr_buf) - nr_len, "nameserver %s\n", ws->dns1_str);
    }
    if (ws->dns2_str[0]) {
        nr_len += snprintf(nr_buf + nr_len, sizeof(nr_buf) - nr_len, "nameserver %s\n", ws->dns2_str);
    }
    if (nr_len > 0) {
        write_text("DEVS:Internet/name_resolution", nr_buf);
    }

    /* DEVS:Internet/routes */
    if (ws->gw_str[0]) {
        char r_buf[128];
        snprintf(r_buf, sizeof(r_buf), "default %s\n", ws->gw_str);
        write_text("DEVS:Internet/routes", r_buf);
    }

    return TRUE;
}

BOOL tn_write_roadshow_interface(const WizardState *ws)
{
    if (!ws || !ws->write_roadshow || ws->selected_hw_idx < 0 || ws->selected_hw_idx >= ws->hw_count) {
        return TRUE;
    }
    const DetectedHw *hw = &ws->hw[ws->selected_hw_idx];

    BPTR lock = CreateDir((CONST_STRPTR)"DEVS:NetInterfaces");
    if (lock) UnLock(lock);

    char ifname[32];
    if (hw->is_wireless) {
        strncpy(ifname, "WiFiPi", sizeof(ifname) - 1);
    } else {
        strncpy(ifname, "Ethernet", sizeof(ifname) - 1);
    }

    char filepath[64];
    snprintf(filepath, sizeof(filepath), "DEVS:NetInterfaces/%s", ifname);

    char buf[512];
    int len = tn_format_roadshow_interface(hw->device_name, hw->unit,
                                           (ws->ip_mode == 0),
                                           ws->ip_str, ws->nm_str,
                                           buf, sizeof(buf));
    if (len <= 0) return FALSE;
    return write_text(filepath, buf);
}


BOOL tn_install_boot_block(BOOL enable)
{
    /* 11l item 2: the byte-exact editor in boot_block.c - the old
     * 64 KB / 256-byte-line in-place rewrite is gone. */
    return tn_boot_block_apply("S:User-Startup", enable);
}

void tn_run_network_tests(WizardState *ws)
{
    if (!ws) return;

    /* 1. Daemon Test - 11o item 2: the daemon's REAL public port
     * name (include/ipc.h), not a made-up short name. */
    Forbid();
    struct MsgPort *port = FindPort((CONST_STRPTR)TOLUNNET_PORT_NAME);
    Permit();

    if (!port) {
        SystemTags((CONST_STRPTR)"Run <NIL: >NIL: C:tolunnet",
                   NP_StackSize, 32768,
                   TAG_END);
        for (int i = 0; i < 50; i++) {
            Delay(5); /* 100ms */
            Forbid();
            port = FindPort((CONST_STRPTR)TOLUNNET_PORT_NAME);
            Permit();
            if (port) break;
        }
    }

    if (port) {
        ws->test_daemon_ok = 1;
        strncpy(ws->test_details[0], "tolunnet 1.2 active", sizeof(ws->test_details[0]) - 1);
        ws->test_advice[0][0] = '\0';
    } else {
        ws->test_daemon_ok = 0;
        strncpy(ws->test_details[0], "Daemon failed to start", sizeof(ws->test_details[0]) - 1);
        strncpy(ws->test_advice[0], "Daemon does not answer. Try: C:tolunnet from a shell", sizeof(ws->test_advice[0]) - 1);
        ws->test_dhcp_ok = 0;
        ws->test_ping_ok = 0;
        ws->test_dns_ok = 0;
        ws->test_http_ok = 0;
        return;
    }

    /* 2. DHCP lease / IP address test - a real check, not an
     * unconditional success. */
    ws->test_dhcp_ok = tn_check_address(ws->test_details[1],
                                        sizeof(ws->test_details[1]));
    if (!ws->test_dhcp_ok) {
        snprintf(ws->test_advice[1], sizeof(ws->test_advice[1]),
                 "No usable address. Check cable and DHCP, then re-run");
    } else {
        ws->test_advice[1][0] = '\0';
    }

    /* 3. Ping Test - 11o item 2: the gateway, else the DNS server,
     * else skipped. */
    {
        const char *phost = NULL;
        if (ws->gw_str[0]) phost = ws->gw_str;
        else if (ws->dns1_str[0]) phost = ws->dns1_str;
        if (phost == NULL) {
            ws->test_ping_ok = 0;
            snprintf(ws->test_details[2], sizeof(ws->test_details[2]),
                     "no gateway configured");
            snprintf(ws->test_advice[2], sizeof(ws->test_advice[2]),
                     "Set a gateway or DNS server, then re-run");
        } else {
            ws->test_ping_ok = tn_check_ping(phost, ws->test_details[2],
                                             sizeof(ws->test_details[2])) ? 1 : 0;
            if (!ws->test_ping_ok) {
                snprintf(ws->test_advice[2], sizeof(ws->test_advice[2]),
                         "Gateway does not answer. Try: ping %s", phost);
            } else {
                ws->test_advice[2][0] = '\0';
            }
        }
    }

    /* 4. DNS Lookup Test - 11o item 1/2: the CONFIGURED server,
     * port 0 (standard port 53). Name = TN_TEST_DNS_NAME; the user
     * can override it with TOLUNNET_TEST_DNS in ENV:. */
    {
        char dns_name[64];
        char dns_ip[32];

        strncpy(dns_name, TN_TEST_DNS_NAME, sizeof(dns_name) - 1);
        dns_name[sizeof(dns_name) - 1] = '\0';
        GetVar((CONST_STRPTR)"TOLUNNET_TEST_DNS", (STRPTR)dns_name,
               (LONG)sizeof(dns_name) - 1, GVF_GLOBAL_ONLY);

        if (ws->dns1_str[0] == '\0') {
            ws->test_dns_ok = 0;
            snprintf(ws->test_details[3], sizeof(ws->test_details[3]),
                     "no DNS server configured");
            snprintf(ws->test_advice[3], sizeof(ws->test_advice[3]),
                     "Set DNS1 in the wizard, then re-run");
        } else {
            ws->test_dns_ok = tn_check_dns(dns_name, ws->dns1_str, 0,
                                           ws->test_details[3],
                                           sizeof(ws->test_details[3]),
                                           dns_ip, sizeof(dns_ip)) ? 1 : 0;
            if (!ws->test_dns_ok) {
                snprintf(ws->test_advice[3], sizeof(ws->test_advice[3]),
                         "Cannot resolve names. Try: nslookup %s %s",
                         dns_name, ws->dns1_str);
            } else {
                ws->test_advice[3][0] = '\0';
            }
        }

        /* 5. HTTP Check Test - connect to the address DNS answered,
         * port 80; skipped when DNS gave nothing. */
        if (dns_ip[0] != '\0') {
            ws->test_http_ok = tn_check_tcp(dns_ip, 80, ws->test_details[4],
                                            sizeof(ws->test_details[4])) ? 1 : 0;
            if (!ws->test_http_ok) {
                snprintf(ws->test_advice[4], sizeof(ws->test_advice[4]),
                         "Web access failed. Try: nc %s 80", dns_ip);
            } else {
                ws->test_advice[4][0] = '\0';
            }
        } else {
            ws->test_http_ok = 0;
            snprintf(ws->test_details[4], sizeof(ws->test_details[4]),
                     "needs DNS");
            snprintf(ws->test_advice[4], sizeof(ws->test_advice[4]),
                     "Fix the DNS check first, then re-run");
        }
    }
}

#else /* Host test stubs */

void tn_run_network_tests(WizardState *ws)
{
    if (!ws) return;
    ws->test_daemon_ok = 1;
    ws->test_dhcp_ok = 1;
    ws->test_ping_ok = 1;
    ws->test_dns_ok = 1;
    ws->test_http_ok = 1;
    strncpy(ws->test_details[0], "tolunnet 1.2 active", sizeof(ws->test_details[0]) - 1);
    strncpy(ws->test_details[1], "DHCP lease OK", sizeof(ws->test_details[1]) - 1);
    strncpy(ws->test_details[2], "Ping verified", sizeof(ws->test_details[2]) - 1);
    strncpy(ws->test_details[3], "DNS active", sizeof(ws->test_details[3]) - 1);
    strncpy(ws->test_details[4], "HTTP operational", sizeof(ws->test_details[4]) - 1);
    ws->test_advice[0][0] = '\0';
    ws->test_advice[1][0] = '\0';
    ws->test_advice[2][0] = '\0';
    ws->test_advice[3][0] = '\0';
    ws->test_advice[4][0] = '\0';
}

BOOL tn_write_tolunnet_config(const WizardState *ws) { (void)ws; return TRUE; }
BOOL tn_write_roadshow_interface(const WizardState *ws) { (void)ws; return TRUE; }
BOOL tn_write_roadshow_internet(const WizardState *ws) { (void)ws; return TRUE; }
BOOL tn_install_boot_block(BOOL enable) { (void)enable; return TRUE; }

#endif

