#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""check_no_nul.py — no raw 0x00 bytes in source files (11y item 4).

A raw NUL inside a char/string literal makes git treat the file as
binary (diffs show `Bin`), so sources must write '\\0' instead. Any
binary fixture is allow-listed by path below; anything else fails.

Run by `make python-checks`. Exit 1 when a non-allow-listed file
contains a 0x00 byte.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCAN_DIRS = ["src", "include", "tests", "ci", "scripts"]
SCAN_FILES = ["Makefile"]

# Binary fixtures allowed to contain NUL bytes (path relative to root,
# '/'-separated; a directory entry allows everything under it).
ALLOW = {
    "ci/tolunnet.info",       # Amiga icon fixture (binary by design)
    "ci/__pycache__",         # generated bytecode
    "scripts/__pycache__",    # generated bytecode
    "tests/host/__pycache__", # generated bytecode
}


def allowed(rel):
    rel = rel.replace("\\", "/")
    if rel in ALLOW:
        return True
    for a in ALLOW:
        if rel.startswith(a + "/"):
            return True
    return False


def main():
    bad = []
    checked = 0
    targets = list(SCAN_FILES)
    for d in SCAN_DIRS:
        base = os.path.join(ROOT, d)
        for dirpath, dirnames, filenames in os.walk(base):
            for fn in filenames:
                targets.append(os.path.relpath(
                    os.path.join(dirpath, fn), ROOT))
    for rel in targets:
        if allowed(rel):
            continue
        path = os.path.join(ROOT, rel)
        if not os.path.isfile(path):
            continue
        with open(path, "rb") as f:
            if b"\x00" in f.read():
                bad.append(rel)
        checked += 1
    if bad:
        print("check_no_nul: FAIL - raw NUL byte in:")
        for rel in bad:
            print("  " + rel)
        return 1
    print("check_no_nul: %d file(s) scanned, 0 raw NUL bytes" % checked)
    return 0


if __name__ == "__main__":
    sys.exit(main())
